#!/usr/bin/env bash
# Installs a webserver, nginx.
#   Install nginx on my server
#+  Nginx should listen on port 80
#+  When querying Nginx at it's root using curl, it must
#++ return a page containing the string Hello World!

sudo apt -y update
sudo apt install -y nginx

sudo ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx restart